// Generated by CIRCT firtool-1.62.0
module top(
  input         clock,
                reset,
  output [15:0] io_outputLed
);

  reg [31:0] count;
  reg [15:0] led;
  always @(posedge clock) begin
    if (reset) begin
      count <= 32'h0;
      led <= 16'h1;
    end
    else begin
      if (count == 32'h4C4B40)
        count <= 32'h0;
      else
        count <= count + 32'h1;
      if (count == 32'h0)
        led <= {led[14:0], led[15]};
    end
  end // always @(posedge)
  assign io_outputLed = led;
endmodule

